### ISSUE TITLE
Review memory allocation and GC configuration

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#243] opened 2016-05-19 00:02 UTC
The jetty9-compat [start script](https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/blob/async-support/jetty9-compat/src/main/docker/jetty_run.sh) contains a calculation of the allowed HEAP_SIZE which is used to start java with `-Xms${HEAP_SIZE} -Xmx${HEAP_SIZE}`

We need to review if this calculation is a good one.  Also we should consider what other GC options/tuning should be done.

**Comment by sbordet** [comment] 2016-05-19 09:41
@gregw not a shell expert, so assuming the calculations are performed using floating point arithmetic (so that `0.8` actually means `8 / 10`).

Consider that the JVM (version 8 and above) will expand anyway the native memory to the maximum available. This is for the MetaSpace and for DirectMemory: if needed, the JVM will occupy all the native memory unless this is limited via explicit flags on command line.

So if the goal is to actually put a hard limit on the RAM that the JVM process can take, the script is not enough.

If the goal is to provide an heuristic of the heap size, then 75%-80% is okay.

**Comment by aozarov** [comment] 2016-05-20 17:18
So now we use that heuristic to cap the heap (and to initialize it to that size, so both -Xmx and -Xms are equal to this value). (1) Do you think we should the cap or just let the JVM expand to the available memory (2) Is the old pattern of setting min/max to be the same to save memory alloc/dealloc is still recommended  (3)  If we do provide a cap the heap via -Xmx what would be a good value that would not deprive the JVM from memory need in other areas (such as native thread stack)? (4) Do you think we should tune the memory required for the native thread stack (1MB per thread does sound excessive to me).

**Comment by sbordet** [comment] 2016-05-20 17:42
(1) Heap should be capped. The JVM uses the remaining _native_ memory for MetaSpace and DirectMemory. If the machine is dedicated to the JVM this is fine. If there are memory watchdogs, then probably is better to cap the whole JVM memory by limiting the MetaSpace and the DirectMemory explictly.

(2) Yes.

(3) That depends on other things. If you have 64 GiB of RAM, the 20% saved will be 12.8 GiB, which is typically plenty for the rest. If you have 4 GiB of RAM, the 20% saved will be 200 MiB which may be a bit small.

(4) Although the stack size is configurable, I would leave it as is.

**Comment by janbartel** [comment] 2016-06-01 22:57
#248 looks like its a duplicate of this issue, but Simone's comments on it are useful.

**Comment by aozarov** [comment] 2016-06-02 00:29
The following are @sbordet suggestions made in #248:

G1 is going to become the standard in JDK 9. 

It is heavily developed and improved in JDK 8 as well (the main development happens in 9, with backports to 8).

G1 behaves typically well in its default configuration, so it's probably what I would start with.

Having said that, GC tuning is heavily dependent on the application allocation profile and memory usage, so it could be that one size does not fit all, but that can only be known on a case-by-case.

I would start with:

```
-XX:+UseG1GC -Xloggc:<log_file> -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+ParallelRefProcEnabled
```

If you need GC pauses different from 250 ms (the default), you can add:

```
-XX:MaxGCPauseMillis=<pause>
```

In addition to these, other useful options that I always add are:

```
-showversion -XX:+PrintCommandLineFlags
```

These will print in the GC log file the Java version and the extended list of flags that the JVM detects at startup, so that in the log file one can know exactly how the JVM was started.

The JVM supports GC log files rotation, if that is needed, via flags:

```
-XX:+UseGCLogFileRotation -XX:GCLogFileSize=<bytes> -XX:NumberOfGCLogFiles=<number> 
```

**Comment by gregw** [comment] 2016-06-08 22:56
I'll make this so this week.

**Closed** 2016-06-09 23:46 UTC
Labels: enhancement, question
