### ISSUE TITLE
GCloudSessionManager doesn't appear to be enabled in non-compat runtimes...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-java-vm-runtime#167] opened 2016-02-03 20:02 UTC
A quick search of the repo, and I notice that gcloudSession isn't used, nor the GCloudSessionIdManager as described in [Chapter 10](http://www.eclipse.org/jetty/documentation/current/session-clustering-gcloud-datastore.html).

Would really be good if we had a way to preserve sessions if a user needed it.

**Comment by ludoch** [comment] 2016-02-03 22:28
Where would you want it? compat or jetty9?
For compat, we already have a session manager.

**Comment by lesv** [comment] 2016-02-03 22:33
Yep - I'd like something for Jetty9

**Comment by lesv** [comment] 2016-02-03 22:33
Datastore, Memecache, Cloud Bigtable (in an ideal world)

**Comment by ludoch** [comment] 2016-02-03 23:37
So non compat, right?

**Comment by lesv** [comment] 2016-02-03 23:52
Yep -- I think we should at least offer sessions -- it's way too hard for users to modify Jetty to roll their own.

**Comment by gregw** [comment] 2016-02-04 05:56
in the current release (9.3.7) we have a simple gcloud session manager. The next major release (9.4.x) will have the new session manager that @janbartel has been working on that will allow memecache and datastore to be used together (and should probably replace the one in compat also).

So we can activate the simple one for now. However, we need to work out how that will work if the image is run on a local docker for testing etc. should we inject an appkey for the datastore and use it remotely or should we just run the hashsession manager....??? Will assign to jan to work out the details.

**Comment by ludoch** [comment] 2016-02-04 09:34
Let's treat it as low priority for now. Compat can be used if a customer
wants session OOB.
In 9.4.x, I would suggest we do a sample on how to enable it in the jetty
image, but it should not be on by default.

**Comment by lesv** [comment] 2016-02-04 18:11
What I would like is that it enables by env vars.  If I give you enough info to do it, it happens, otherwise, it doesn't.

**Comment by janbartel** [comment] 2016-02-05 08:50
@lesv the jetty GCloudSessionManager in jetty-9.3.x should certainly be able to be activated. We'd have to do some swizzling of env vars into jetty properties (for properties see list in http://www.eclipse.org/jetty/documentation/current/session-clustering-gcloud-datastore.html) for contacting a remote gcloud store. Env vars are already used for contacting a local dev gcloud server. One configuration issue we would have to consider is how to obtain a unique nodeid for each jetty server enabled for gcloud sessions.  Whilst the gcloud session config properties would be invariant for each deployment, each deployment would need its own unique nodeId. I'll check with @gregw if there is anything we could use for that already in place.

One difference between the jetty gcloud session manager and the compat one - as @gregw mentioned - is that the gcloud session manager does NOT use memcache as a write-through cache for sessions in the way that the compat session manager does.  In the 9.3.x version, sessions are retained in memory, and written through to the gcloud store when a request exists iff there have been changes to session data. 

One advantage of the jetty gcloud session manager over the compat one is that multiple concurrent requests for the same session id will automatically use the same session object. In the compat one, each request will obtain a new session instance leading to unpredictable outcomes when session data is written.

Also as @gregw mentioned, we're working on a new session manager architecture for jetty-9.4 where using memcache as a cache in front of gcloud datastore will be possible, as will adding in other features such as passivating out to gcloud in-memory sessions that have been idle for a configurable amount of time.

Jan

**Comment by gregw** [comment] 2016-04-28 00:24
#183 has been closed as a duplicate of this issue.  #188 had also become a duplicate.

An example non compat session clustering example has been prepared at GoogleCloudPlatform/java-docs-samples#123, but some more work is needed

**Comment by gregw** [comment] 2016-09-08 01:37
obsoleted by https://github.com/GoogleCloudPlatform/jetty-runtime/issues/5

**Closed by gregw** 2016-09-08 01:37 UTC
Labels: enhancement
