### ISSUE TITLE
mapping override of webdefault.xml

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#133] opened 2015-12-03 16:03 UTC
When a servlet is set to "/" in the web.xml, it will override the webdefault.xml
However, if I use @WebServlet(name = "helloworld", urlPatterns = { "/" }) I get the following error when running locally with `mvn clean gcloud:run : 
[INFO] java.lang.IllegalStateException: Multiple servlets map to path: /: helloworld,default

**Comment by gregw** [comment] 2015-12-03 21:09
Looks like a bug.  I have raised https://bugs.eclipse.org/bugs/show_bug.cgi?id=483620

**Comment by janbartel** [comment] 2015-12-04 05:54
@ludoch, which version of jetty is this happening with? I've tried this with standard distributions of jetty-9.2.12 and master  and I can't seem to reproduce this behaviour. Were you using quickstart or not? Do you have a test harness to reproduce this?

**Comment by ludoch** [comment] 2015-12-07 20:39
I see that in order to generate the app.yaml with quickstart, we first remove some servlets:
in 
https://code.google.com/p/googleappengine/source/browse/trunk/java/src/main/com/google/appenginehttps://code.google.com/p/googleappengine/source/browse/trunk/java/src/main/com/google/appengine/tools/admin/Application.java#1382

 getFilteredQuickstartDoc()...

Removed:
  <filter-mapping>
    <filter-name>AbandonedTransactionDetector</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>
  <filter-mapping>
    <filter-name>SaveSessionFilter</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>
  <filter-mapping>
    <filter-name>_ah_ParseBlobUploadFilter</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>
  <filter-mapping>
    <filter-name>_ah_VmStopFilter</filter-name>
    <url-pattern>/_ah/stop</url-pattern>
  </filter-mapping>


and  removed:

  <servlet-mapping>
    <servlet-name>_ah_health</servlet-name>
    <url-pattern>/_ah/health</url-pattern>
  </servlet-mapping>
  <servlet-mapping>
    <servlet-name>_ah_sessioncleanup</servlet-name>
    <url-pattern>/_ah/sessioncleanup</url-pattern>
  </servlet-mapping>
  <servlet-mapping>
    <servlet-name>_ah_warmup</servlet-name>
    <url-pattern>/_ah/warmup</url-pattern>
  </servlet-mapping>
  <servlet-mapping>
    <servlet-name>_ah_queue_deferred</servlet-name>
    <url-pattern>/_ah/queue/__deferred__</url-pattern>
  </servlet-mapping>
  <servlet-mapping>
    <servlet-name>default</servlet-name>
    <url-pattern>/</url-pattern>
  </servlet-mapping>
  <servlet-mapping>

See the last mapping we remove:     
<servlet-name>default</servlet-name>
    <url-pattern>/</url-pattern>

I think this is the root cause.

See the javadoc:
 /**
   * Removes mappings from quickstart-web.xml that come from webdefault.xml.
   *
   * The quickstart-web.xml generated by the quickstartgenerator process includes
   * the contents of the user's web.xml, entries derived from Java annotations,
   * and entries derived from the contents of webdefault.xml. All of those are
   * appropriate for the Java web server. But when generating an app.yaml for
   * appcfg or dev_appserver, the webdefault.xml entries are not appropriate, since
   * app.yaml should only reflect what is specific to the user's app. So this
   * method returns a modified min-quickstart-web Document from which the webdefault.xml
   * entries have been removed. Specifically, we look at the <url-pattern> inside
   * every <servlet-mapping> or <filter-mapping> element in webdefault.xml to
   * determine default patterns; then we look at those elements inside
   * quickstart-web.xml and remove any whose <url-pattern> is one of the default
   * patterns.
   *
   * @return a filtered quickstart Document object appropriate for translation to app.yaml
   */

**Comment by janbartel** [comment] 2015-12-09 02:46
@ludoch if you generate quickstart with -Dorg.eclipse.jetty.quickstart.LEVEL=DEBUG, we add additional info regarding the origin of each element in the generated descriptor.

For example, here is a sample of the generated quickstart xml elements for the DefaultServlet added from webdefault.xml, and the com.acme.Other servlet which is mapped to / via an annotation:

  <servlet source="DESCRIPTOR">
    <servlet-name>default</servlet-name>
    <servlet-class origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">org.eclipse.jetty.servlet.DefaultServlet</servlet-class>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>aliases</param-name>
      <param-value>false</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>dirAllowed</param-name>
      <param-value>true</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>maxCacheSize</param-name>
      <param-value>256000000</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>maxCachedFileSize</param-name>
      <param-value>200000000</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>welcomeServlets</param-name>
      <param-value>false</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>useFileMappedBuffer</param-name>
      <param-value>true</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>gzip</param-name>
      <param-value>false</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>acceptRanges</param-name>
      <param-value>true</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>etags</param-name>
      <param-value>false</param-value>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>etags</param-name>
      <param-value>false</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>maxCachedFiles</param-name>
      <param-value>2048</param-value>
    </init-param>
    <init-param origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
      <param-name>redirectWelcome</param-name>
      <param-value>false</param-value>
    </init-param>
    <load-on-startup>0</load-on-startup>
    <async-supported>false</async-supported>
  </servlet>
  <servlet-mapping origin="DefaultsDescriptor(file:/home/janb/usr_local_java/jetty/jetty-distribution-9.2.12.v20150709/etc/webdefault.xml)">
    <servlet-name>default</servlet-name>
    <url-pattern>/</url-pattern>
  </servlet-mapping>


  <servlet source="ANNOTATION">
    <servlet-name>com.acme.test.Other</servlet-name>
    <servlet-class origin="@WebServlet on com.acme.test.Other">com.acme.test.Other</servlet-class>
    <async-supported origin="@WebServlet on com.acme.test.Other">false</async-supported>
  </servlet>
  <servlet-mapping origin="@WebServlet on com.acme.test.Other">
    <servlet-name>com.acme.test.Other</servlet-name>
    <url-pattern>/</url-pattern>
  </servlet-mapping>


So, if you want to be able to remove elements that originate from webdefaults.xml you should be able to delete those elements that have origin starting with "DefaultsDescriptor".

I am also working on a patch to jetty to make sure that if a servlet mapping from webdefaults.xml is overridden by one from an annotation, it never appears in quickstart-web.xml.  Note that this is already the case with servlet mappings in webdefaults.xml that are  overridden by web.xml or a fragment.xml (ie they never appear in quickstart-web.xml).

Jan

**Comment by janbartel** [comment] 2015-12-10 00:03
@ludoch OK, now I've been able to reproduce the problem. The problem occurs not when running the webapp when we generate the quickstart-web.xml, but when running the webapp later on, purely off the previously generated quickstart-web.xml.

The fix I mentioned before for https://bugs.eclipse.org/bugs/show_bug.cgi?id=483620 solves the problem. The fix is checked in to jetty-9.2.x, jetty-9.3.x and jetty master branches and will be in the next release for all of those version streams.

I'll leave this issue open until appengine is able to be updated to the latest version of one of those streams.

**Comment by gregw** [comment] 2015-12-11 02:39
@ludoch I'm trying to do a manual override of the webdefault.xml file in the SDK.  I've found every instance of the file (and there are at least 9 copies in the SDK!) and replaced them with the version I need for async support, yet somehow the quickstart.xml is still being generated with the old webdefault.xml!

You can see below that I have totally removed support for the TransactionCleanupFilter, yet it is still generated?    Where else could the SDK be getting the xml from?  From the maven plugin?

```
gregw@Tile440: /usr/local/share/google/google-cloud-sdk
[2194] find -name '*.jar' | while read JAR; do jar tf $JAR | egrep webdefault.xml | while read XML; do echo $JAR $XML; jar xf $JAR $XML; egrep TransactionCleanupFilter $XML; rm -fr $XML ; done ; done
./platform/google_appengine/google/appengine/tools/java/lib/java-managed-vm/appengine-java-vmruntime/quickstartgenerator.jar com/google/apphosting/vmruntime/jetty9/webdefault.xml
./platform/google_appengine/google/appengine/tools/java/lib/java-managed-vm/appengine-java-vmruntime/lib/jetty-webapp-9.2.10.v20150310.jar org/eclipse/jetty/webapp/webdefault.xml
./platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com/google/appengine/tools/development/devappserver2/webdefault.xml
./platform/google_appengine/google/appengine/tools/java/lib/impl/appengine-local-runtime.jar com/google/appengine/tools/development/devappserver2/webdefault.xml
./platform/google_appengine/google/appengine/tools/java/lib/impl/appengine-local-runtime.jar com/google/appengine/tools/development/webdefault.xml
./platform/google_appengine/google/appengine/tools/java/lib/impl/appengine-local-runtime.jar org/mortbay/jetty/servlet/webdefault.xml
./platform/google_appengine/google/appengine/tools/java/lib/impl/appengine-local-runtime.jar org/mortbay/jetty/webapp/webdefault.xml

gregw@Tile440: /usr/local/share/google/google-cloud-sdk
[2195] find -name 'webdefault*.xml' | xargs egrep TransactionCleanupFilter

```

**Comment by ludoch** [comment] 2015-12-11 03:55
Did you solve this?

**Comment by gregw** [comment] 2015-12-11 05:32
No.  In the end i just modified the staged webapp and then deployed.  The
xml must come from a maven Pugin dependency. I'll work out which one next
week.

**Closed** 2016-06-08 23:27 UTC
Labels: Fixed In Async
