### ISSUE TITLE
ASYNC jetty9-compat image - Incorrect URL generated in a compat image for login

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-java-vm-runtime#164] opened 2016-01-26 19:25 UTC
https://accounts.google.com/ServiceLogin?
service=ah
&passive=true
&continue=https%3A%2F%2Fappengine.google.com%2F_ah%2Fconflogin%3Fcontinue%3Dhttp%3A%2F%2F0.20160126t110119.lesv-004.appspot.com%2Fguestbook.jsp
&ltmpl=gm
&shdf=ChQLEgZxxxxxxxxxxx

1. Using https://github.com/GoogleCloudPlatform/appengine-java-vm-guestbook-extras/
2. `cd stage3; mvn gcloud:deploy`; visit site - logout, login note URL's.
https://accounts.google.com/ServiceLogin?
service=ah
&passive=true
&continue=https%3A%2F%2Fappengine.google.com%2F_ah%2Fconflogin%3Fcontinue%3Dhttps%3A%2F%2F20160126t111625-dot-lesv-004.appspot.com%2F
&ltmpl=gm
&shdf=ChQLEgZxxxxxxx

Note - **https://20160126t111625.lesv-004.appspot.com/guestbook.jsp**

3. `vi src/main/webapp/Dockerfile`
4. add the suffix **:githubheadasync** to the FROM line
5. `mvn gcloud:deploy`

The Redirect URL on the ASYNC is **http://0.20160126t110119.lesv-004.appspot.com/guestbook.jsp** which is wrong for several reasons:

  a. It's to a specific Instance
  b. It's not using https

The correct redirect URL should be **https://20160126t110119.lesv-004.appspot.com/guestbook.jsp**

**Comment by lesv** [comment] 2016-01-26 19:25
@ludoch This is IMPORTANT

**Comment by ludoch** [comment] 2016-01-26 23:46
For Greg, when he is back next week.

**Comment by ludoch** [comment] 2016-01-27 00:29
Relevant code path: https://code.google.com/p/googleappengine/source/browse/trunk/java/src/main/com/google/appengine/api/users/UserServiceImpl.java

**Comment by lesv** [comment] 2016-01-27 01:51
If I add a security constraint to the web.xml of CONFIDENTIAL, this problem doesn't occur, the earlier jetty-compat didn't require this.

**Comment by joakime** [comment] 2016-01-27 02:05
Interesting find about the CONFIDENTIAL bit, I wonder if its related to https://bugs.eclipse.org/486511 (recently identified and fixed in Jetty 9.3.x branches)

**Comment by ludoch** [comment] 2016-01-27 03:24
haha!

**Comment by gregw** [comment] 2016-01-27 09:29
I'm not due back until mid next week. But as i have torn a calf muscle and
I'm not skiing anymore and may have time for a look tomorrow.

Joakim, was that fix put into 9.3.7 for the https?

For the specific server names, does the proxy set any headers to say what
it is? If so it is easy for us to use that.  Or does it rewrite the normal
host header with a specific instance? If so then we may need to do a
rewrite filter.

Getting the full headers of a request would help.

**Comment by gregw** [comment] 2016-02-02 08:26
@ludoch both the host name and scheme used for redirects can be affected by the proxy environment and headers injected by the proxy.   We inherited the following configuration from prior versions, but it is not currently used:
```
      <!-- Requests arriving through App Engine should be treated as forwarded. -->
      <Call name="addCustomizer">
        <Arg>
          <New class="org.eclipse.jetty.server.ForwardedRequestCustomizer">
            <Set name="forwardedHostHeader">Host</Set>
            <Set name="forwardedServerHeader">Host</Set>
            <Set name="forwardedForHeader">X-AppEngine-User-IP</Set>
          </New>
        </Arg>
       </Call>
```
This configuration doesn't look exactly right - not sure about the need to set the Host header.  Also it doesn't handle a forwarded protocol.

So I'm guessing we need to properly configure the request customization - specially if the proxy is rewriting the host header with the specific instance.   Also do we assume all requests are https or is there an indication in the headers?

I'll do some experiments to determine the headers - but it would be good to know what they are intended to be and how http vs https traffic is intended to handled/offloaded.

cheers

**Comment by gregw** [comment] 2016-02-02 18:06
@lesv I just failed to reproduce with the current githubheadasync label.  All the URLs in the params looked correct.

I'll try a few more variations tomorrow.

**Comment by lesv** [comment] 2016-02-02 21:18
I'll try to replicate tonight.

On Tue, Feb 2, 2016 at 10:06 AM, Greg Wilkins <notifications@github.com>
wrote:

> @lesv <https://github.com/lesv> I just failed to reproduce with the
> current githubheadasync label. All the URLs in the params looked correct.
>
> I'll try a few more variations tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/issues/164#issuecomment-178726274>
> .
>



-- 


*  •  **Les Vogel*
*  •  *Cloud Developer Relations
*  •  *lesv@google.com
*  •  *+1-4 <%2B1-650-338-7103>08-676-7023

**Comment by lesv** [comment] 2016-02-03 00:11
It seems to work for me now.

**Comment by ludoch** [comment] 2016-02-03 00:42
Nothing changed there. Weird, but glad it works

**Comment by gregw** [comment] 2016-02-03 06:37
OK I have reproduced the problem and investigated a bit more.    This version of [guestbook JSP](https://20160203t071839-dot-jetty9-work.appspot.com/) is updated to printout some extra info:
```
getRequestURI()=/guestbook.jsp
userService.createLogoutURL(request.getRequestURI())=http://0.20160203t071839.jetty9-work.appspot.com/_ah/logout?continue=https://www.google.com/accounts/Logout%3Fcontinue%3Dhttps://appengine.google.com/_ah/logout%253Fcontinue%253Dhttp://0.20160203t071839.jetty9-work.appspot.com/guestbook.jsp%26service%3Dah
```
So you can see both the wrong scheme and wrong host in the output of `UserService.createLogoutURL(String)`.     I don't have the source for that method (links?), but I've been trying to work out if there is anything that the server is setting that might be giving the scheme/host incorrectly?

So I added a [dump.jsp](https://20160203t071839-dot-jetty9-work.appspot.com/dump.jsp) and [DumpServlet](https://20160203t071839-dot-jetty9-work.appspot.com/dump/info) to the webapp.  In both those, you can see the correct scheme and no mention of the instance in any host name.   

Thus the scheme and host name must be derived by the UserService through some other mechanism?      I need that source before I can determine exactly what the issue is.

**Comment by ludoch** [comment] 2016-02-03 10:04
Sending you the info.

**Comment by gregw** [comment] 2016-02-05 09:39
Looking at the code, I now suspect that the wrong values are being taken from environment variables, however deployment is currently broken (I just get 503s) so I can't verify.

I'm out of time this week, but will investigate more next week.

**Comment by ludoch** [comment] 2016-02-05 15:59
Now you got me intrigued!!!

**Comment by ludoch** [comment] 2016-02-05 16:03
From https://20160203t071839-dot-jetty9-work.appspot.com/SystemViewer
I see these:
- System.getenv()
-
PATH=/usr/local/jetty/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- APPENGINE_LOADBALANCER=
- MEMCACHE_ENV_DEBIAN_FRONTEND=noninteractive
- RUNTIME_DIR=/var/lib/jetty
- MODULE_YAML_PATH=app.yaml
- MEMCACHE_PORT_11211_TCP_ADDR=172.17.0.3
- GAE_LONG_APP_ID=jetty9-work
- APPENGINE_LOADBALANCER_IP=
- GAE_MINOR_VERSION=390434114197675026
- MEMCACHE_NAME=/gaeapp/memcache
- MEMCACHE_PORT=tcp://172.17.0.3:11211
- SERVER_SOFTWARE=Google App Engine/1.9.32
- MEMCACHE_PORT_11211_TCP_PORT=11211
- GAE_MODULE_VERSION=20160203t071839
- MEMCACHE_PORT_11211_TCP_PROTO=tcp
- GAE_APPENGINE_HOSTNAME=jetty9-work.appspot.com
- JETTY_HOME=/usr/local/jetty
- GAE_VM=true
- USE_MVM_AGENT=true
- PWD=/var/lib/jetty
- GAE_PARTITION=s
- _=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
- JETTY_BASE=/var/lib/jetty
- GAE_MODULE_NAME=default
- OLDPWD=/var/lib/jetty/webapps/root
- TMPDIR=/tmp/jetty
- DEBIAN_FRONTEND=noninteractive
- HOSTNAME=4decf4ae8b8b
- GAE_MODULE_INSTANCE=0
- MEMCACHE_PORT_11211_TCP=tcp://172.17.0.3:11211
- GAE_AFFINITY=true
- HOME=/root
- SHLVL=1

**Comment by gregw** [comment] 2016-02-05 21:32
Ah - I've been misreading the code and the host/port it was looking up were for the API server, not the HTTP server (looked for in API_HOST and API_PORT).

But interesting that GAE_MODULE_INSTANCE=0 is there as that is so far the only indication of the instance itself.   So if the URL is being generated incorrectly due to something in compat, then it could be based on GAE_MODULE_INSTANCE, which is definitely read by the VmApiProxyEnvironment.

Hmmm but that is going to be the same for the default environment and the per request environment, so I don't see how the async changes can affect that.... and tracing it through to com.google.apphosting.vmruntime.VmApiProxyDelegate.createRequest(VmApiProxyEnvironment, String, String, byte[], int)  I can see that the environment instance is not encoded into the API request.  

So I think the env stuff is a red herring.    I can't see how client side can effect the instance being put into the UserService URLs.  I think we need to see the server side code.

**Comment by ludoch** [comment] 2016-02-05 22:02
Yes, Filing an internal bug.

**Comment by ludoch** [comment] 2016-02-12 01:50
https://lesv-004.appspot.com starts with https and sign in link.
Sign in, then 
you go to http://0.20160211t173320.lesv-004.appspot.com/guestbook.jsp
which is now https... So same bug

**Comment by ludoch** [comment] 2016-02-12 01:51
sample deployed with 
 FROM gcr.io/google_appengine/jetty9-compat:ludoticketoldjetty

**Comment by ludoch** [comment] 2016-02-12 04:02
I confirm I can reproduce with the image from head just modified to use the global API ticket, so this is not related to the ASYNC branch... It has to be on the server impl for the user service via this global ticket.

**Comment by gregw** [comment] 2016-02-22 11:55
@ludoch 

I've made some progress on the UserService [workaround](https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/compare/async-support...jetty-project:async-support-hacked), but it needs more work. 

The workaround makes the RPC call, then takes the resulting URL and fixes the scheme and host.   That part works fine!  BUT the resulting URL actually contains nested URLs (2 deep) as URL parameters of URL parameters! eg.

```
getRequestURI()=/guestbook.jsp
userService.createLogoutURL(request.getRequestURI())=https://jetty9-work.appspot.com/_ah/logout?continue=https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout%253Fcontinue%253Dhttp://0.20160222t120239.jetty9-work.appspot.com/guestbook.jsp&service=ah
```

So to really work around this, I'm going to have to delve deep into the resulting URL looking for nested URLs.  It also will need conversion of hosts
like 0.123456.jetty9-work.appspot.com, not just to 123456.jetty9-work.appspot.com, but to 123456-dot-jetty9-work.appspot.com.   

Doable, but either complex to be general or very specific to this particular form of URL (and thus fragile).

I guess we don't have any idea when a server side fix will come?  Or is there any indication of why the async branch is tickling this bug when master is not???      Shall I proceed or hold?  Also what form of env variable do you want if I proceed? something to turn it on, or something to turn it off?

**Comment by ludoch** [comment] 2016-02-22 15:48
No eta on our side, but I am putting more pressure as it can be seen in
Python as well. This is really because of this new global API ticket value.
When the ticket comes from the http header, the API works. Master is using
the header value of the ticket.
Do not put too much effort on it and treat is as a hack that may allow us
to have more usage, and find other bugs down the road.
I would turn the hack on by default.

**Comment by gregw** [comment] 2016-02-22 18:22
Ah - and we can't switch to using the header value of the ticket, as it is not valid after the response is committed.... and since we are no longer using the delayed response technique, the commit can come before our API usage.

OK, I'll do a very hacky string substitution!

**Comment by ludoch** [comment] 2016-02-24 20:52
Closing for now. We will remove the workaround when needed.

**Closed by ludoch** 2016-02-24 20:52 UTC
Labels: bug
