### ISSUE TITLE
logging doesn't work locally

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-java-vm-runtime#136] opened 2015-12-16 23:55 UTC
In my appengine-web.xml I enable the following lines:

    <system-properties>
      <property name="java.util.logging.config.file" value="WEB-INF/logging.properties"/>
      <property name="log4j.debug" value="true" />
    </system-properties>

I've tried "/WEB-INF/logging.properties", and a full path "/Users/.../target/appengine-staging/WEB-INF/logging.properties".  The /WEB-INF says file not found, but the others work.

On my machine, in [my project](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/managed-vm-gae), doing `mvn gcloud:run` I see:

Temporary staging for module default directory left in /Users/lesv/github/cloud-bigtable-examples/java/managed-vm-gae/target/appengine-staging
[INFO] Running python -S /Users/lesv/google-cloud-sdk/platform/google_appengine/dev_appserver.py --skip_sdk_update_check=true -A app /Users/lesv/github/cloud-bigtable-examples/java/managed-vm-gae/target/bigtable-hello-1.0-SNAPSHOT/app.yaml --jvm_flag=-Xbootclasspath/p:/Users/lesv/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.3.v20150130/alpn-boot-8.1.3.v20150130.jar --runtime=java
[INFO] INFO     2015-12-16 23:50:27,763 application_configuration.py:431] No version specified. Generated version id: 20151216t235027
[INFO] INFO     2015-12-16 23:50:27,764 devappserver2.py:769] Skipping SDK update check.
[INFO] INFO     2015-12-16 23:50:27,818 api_server.py:205] Starting API server at: http://localhost:60036
[INFO] INFO     2015-12-16 23:50:27,827 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
[INFO] INFO     2015-12-16 23:50:27,834 admin_server.py:116] Starting admin server at: http://localhost:8000
**[INFO] 2015-12-16 23:50:28.170:INFO::main: Logging initialized @326ms**
**[INFO] 2015-12-16 23:50:28.362:INFO:oejs.Server:main: jetty-9.2.10.v20150310**
**[INFO] 2015-12-16 23:50:28.376:WARN:oejsh.RequestLogHandler:main: !RequestLog**
[INFO] 2015-12-16 23:50:28.378:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:/Users/lesv/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/jetty-base-sdk/contexts/] at interval 1
[INFO] Dec 16, 2015 11:50:28 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
[INFO] INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
[INFO] Dec 16, 2015 11:50:28 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
[INFO] INFO: Meta-data 'attributes/gae_appengine_hostname' path retrieval error: metadata
[INFO] Dec 16, 2015 11:50:28 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
[INFO] INFO: Meta-data 'attributes/gae_use_nginx_proxy' path retrieval error: metadata
[INFO] Dec 16, 2015 11:50:28 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
[INFO] INFO: Meta-data 'attributes/gae_tmp_force_reuse_api_connection' path retrieval error: metadata
**[INFO] 2015-12-16 23:50:32.511:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty**
**[INFO] log4j:WARN No appenders could be found for logger (com.google.cloud.bigtable.hbase.BigtableOptionsFactory).**
**[INFO] log4j:WARN Please initialize the log4j system properly.**
**[INFO] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.**

**Comment by gregw** [comment] 2015-12-17 00:20
This is a duplicate of #124

**Comment by lesv** [comment] 2015-12-17 00:55
I changed my logging.properties .level=ALL and I see some different stuff, but still none of my logging.

````
[INFO] log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
[INFO] log4j:WARN Please initialize the log4j system properly.
[INFO] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[INFO] SLF4J: Defaulting to no-operation (NOP) logger implementation
[INFO] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
````

I'm logging using the servlet .log, so it shouldn't be dependant on any loggers that hbase might include (like SLF4J).  (I probably need to add the SLF4J servlet critter).

**Comment by gregw** [comment] 2016-01-08 00:14
Partial fix in master, full fix in async-support. See #124 for details.

**Closed by gregw** 2016-01-08 00:14 UTC

**Comment by ludoch** [comment] 2016-01-08 19:17
You can try the full fix with a custom runtime: Just add the Dockerfile in src/main/webapp

FROM gcr.io/google_appengine/jetty9-compat:githubheadasync
ADD . /app
