### ISSUE TITLE
 Remove from the jetty image (or hide from the application) the AE API jar

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/appengine-java-vm-runtime#259] opened 2016-05-25 17:43 UTC
Currently we *remove* the AE API jar provided by the application and use the same one that is bundled with Jetty (needed for session management). 

I think ideally we should hide (different class-loader) the AE API jar that is bundled with Jetty and keep AE API jar that is bundled with the application. 

I also think that it would be nice if we, at least, warn during deployment time if that jar is missing from compat mode.

Also, it would be nice if dev appsesrver would be consistent with production and not expose the AE API jar if not provided by the user.

**Comment by gregw** [comment] 2016-05-26 23:48
This can be achieved with the jetty server class mechanism.      We can manually update the list of hidden packages/classes, but a better approach would be to use maven to automatically generate the list.

**Comment by aozarov** [comment] 2016-05-27 17:34
I think this issue is also related to #253

**Comment by gregw** [comment] 2016-06-02 00:53
@aozarov Just to be clear,  the "remove the AE API jar provided by the application" is done by the SDK?   In which case if we hide the AE API jar from the webapp we will break old versions of the SDK.

Instead, we can be dynamic and examine the webapp for a jar providing com/google/appengine/api to trigger specific behaviour, for which I see two options:

1. We always hide com.google.* packages (and their dependencies) from the webapp.  If the webapp does not have it's own com.google.appengine.api then we add the api jar (with all its bundled dependencies and repackaging) to the webapp classloader.
2. We only hide com.google.* from the webapp if it has it's own com.google.appengine.api, otherwise we allow it to see the classes from the server classloader

Option 1 is simplest and more robust for changes to the contents of the jar, but will result in more memory usage as the api jar is loaded twice.  

Option 2 saves memory (but only while the SDK is removing the API jar) but is more complex choosing exactly what packages to expose is not obvious and may be subject to change.

**Comment by aozarov** [comment] 2016-06-02 01:27
> @aozarov Just to be clear, the "remove the AE API jar provided by the application" is done by the SDK? In which case if we hide the AE API jar from the webapp we will break old versions of the SDK.

Yes, this is done (according to @ludoch) by the SDK (I think in the staging phase).
Indeed that means it is a breaking change but I think we should do that. @ludoch may disagree.

If possible to restrict it only for flex deployments and therefore minimize the backward compatibility
issues I would take that. One option is to change the staging to stop removing the api jar only for flex
and making this change to the runtime only for flex (by either saying async-support branch is only
for flex or changing the class-loading behavour based on flex or not). @ludoch any thoughts about it?

**Comment by gregw** [comment] 2016-06-02 03:28
@aozarov @ludoch If we do it dynamically, then it is not a breaking change.   If the api-jar is removed by the SDK, we can put it back either as a jar or my exposing server classes.  If it is not removed, we hide the container jar, so there are different versions.      This should then work with either old or new SDKs

**Comment by aozarov** [comment] 2016-06-02 20:20
@gregw my fear is that if we have this option it will be forever abused and will limit our ability
to use internally any version we want.

**Comment by gregw** [comment] 2016-06-02 22:41
@aozarov If we dynamically provide the jar by adding it to the classpath rather than exposing the version used by the server, then we are free to use one version ourselves and have a different version that we add to the webapp.   This is a very good argument for adding the jar rather than exposing server classes.

**Comment by aozarov** [comment] 2016-06-03 00:28
Yes, if we had to choose option (1) or option (2) I would go with option (1).
It looks like that is your preference too. I am still in favor of not providing an api jar if the user didn't
provide one as that is consistent with AE classic (the expectation was that user should test their code - dev appserver with the same jar that they will use in production). Also, what API jar version are we going to pick? latest pulled at runtime or one that is baked in the image?

We always wanted to have the option of making backward incompatible changes to the API. That is only possible if we make sure deployed apps are pinned to a specific version (which they build their app with). Maybe we gave up on this idea...

**Comment by gregw** [comment] 2016-06-03 03:18
OK, so unless @ludoch  thinks otherwise, I'll prepare a PR that hides all the api classes and their dependencies.

This will break any deployments from an SDK that does remove the API jar.  If this proves to be a problem, I can create a second PR that will optionally add an API jar that is versioned independently of what we use.

**Comment by aozarov** [comment] 2016-06-03 18:07
I spoke with @ludoch. I think he agrees with with however he would like a transitional stage that will use option (1)  but also omit a warning log saying that the application should be deployed using the newest SDK (that enforce the application to include the api jar and does not remove it) if we detect that
the application is missing it. Once we stop supporting `vm=true` we can remove the check and copying
the jar to the user's lib path.

**Comment by gregw** [comment] 2016-06-10 06:07
@ludoch @aozarov I've tried out hiding the api jar used by the container, but many test servlets do not work, even if I add back a WEB-INF version of the api jar.    The problem appears to be that many of the test servlets (at least) use ApiProxy.getCurrentEnvironment().  Because they are loading the ApiProxy class from the WEB-INF version of the jar, they are seeing a different threadlocal than the container.  Thus they get a null environment and it all goes bad from there.

So I've been able to make it work if I expose just:

    "com.google.apphosting.api.ApiProxy",
    "com.google.apphosting.api.ApiProxy.Environment",
    "javax.mail"

The first two give access to the containers environment and luckily the signature of the Environment class is written in terms of java.lang classes, so it can be used without exposing further classes.
Is accessing the ApiProxy like that expected to be done, or only in our test servlets and internal filters?

I'm not exactly sure why javax.mail is needed... I have yet to investigate, nor to check why the testwebapp is not bundling that if it expects to use it?

**Comment by gregw** [comment] 2016-06-10 07:17
Hmmm there is also a problem with the SessionManager, because it serializes a SessionData object that contains attribute values from the application.  Thus when it is deserialized its classloader needs to see both application classes and container classes.

In Jetty we avoid this issue by not serializing the SessionData class itself, just a sequence of its components that are all either java.lang classes or application classes, and thus all visible from the webapp context classloader.

I'm guessing we can't change the DB format of session storage?

So we could either just expose SessionData class as well, or selectively open up the classloader wall during session deserialization.

**Comment by ludoch** [comment] 2016-06-10 16:04
GAE standard (v1) implementation uses this exact list of shared classes from the API jars:
com/google/appengine/api/LifecycleManager$1.class
com/google/appengine/api/LifecycleManager$ShutdownHook.class
com/google/appengine/api/LifecycleManager.class
com/google/apphosting/api/ApiProxy$1.class
com/google/apphosting/api/ApiProxy$ApiConfig.class
com/google/apphosting/api/ApiProxy$ApiDeadlineExceededException.class
com/google/apphosting/api/ApiProxy$ApiProxyException.class
com/google/apphosting/api/ApiProxy$ApiResultFuture.class
com/google/apphosting/api/ApiProxy$ApplicationException.class
com/google/apphosting/api/ApiProxy$ArgumentException.class
com/google/apphosting/api/ApiProxy$CallNotFoundException.class
com/google/apphosting/api/ApiProxy$CancelledException.class
com/google/apphosting/api/ApiProxy$CapabilityDisabledException.class
com/google/apphosting/api/ApiProxy$Delegate.class
com/google/apphosting/api/ApiProxy$Environment.class
com/google/apphosting/api/ApiProxy$EnvironmentFactory.class
com/google/apphosting/api/ApiProxy$FeatureNotEnabledException.class
com/google/apphosting/api/ApiProxy$LogRecord$Level.class
com/google/apphosting/api/ApiProxy$LogRecord.class
com/google/apphosting/api/ApiProxy$OverQuotaException.class
com/google/apphosting/api/ApiProxy$RPCFailedException.class
com/google/apphosting/api/ApiProxy$RequestTooLargeException.class
com/google/apphosting/api/ApiProxy$ResponseTooLargeException.class
com/google/apphosting/api/ApiProxy$UnknownException.class
com/google/apphosting/api/ApiProxy.class
com/google/apphosting/api/ApiStats.class
com/google/apphosting/api/CloudTrace.class
com/google/apphosting/api/CloudTraceContext.class
com/google/apphosting/api/DeadlineExceededException.class
com/google/apphosting/runtime/SessionData.class
com/google/apphosting/runtime/UncatchableError.class

We should mirror this sharing in Flex.

**Comment by gregw** [comment] 2016-06-15 03:44
Thanks @ludoch, I've implemented that exact list.  

However I'm now having problems with the transaction completion mechanism. The context needs to be able to rollback any transactions found at request completion by `DatastoreServiceFactory.getDatastoreService().getActiveTransactions()` but that is not one of the exposed classes.   So I'm using reflection to look into the context classloader and try to do that rollback.    Only marginal success so far.... stay tuned....

**Comment by gregw** [comment] 2016-07-13 01:01
The following was reported from an application using the latest image after the merge:
```
org.eclipse.jetty.webapp.WebAppContext doStart: Failed startup of context c.g.a.v.j.VmRuntimeWebAppContext@704921a5{/,file:///var/lib/jetty/webapps/root/,UNAVAILABLE}
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
    at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
    at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
    at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
    at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
    at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
    at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
    at java.lang.Class.createAnnotationData(Class.java:3521)
    at java.lang.Class.annotationData(Class.java:3510)
    at java.lang.Class.getAnnotation(Class.java:3415)
    at org.eclipse.jetty.annotations.AnnotationConfiguration.createServletContainerInitializerAnnotationHandlers(AnnotationConfiguration.java:663)
    at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:444)
    at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:491)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1336)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
    at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doStart(VmRuntimeWebAppContext.java:189)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppDeployer.doStart(VmRuntimeWebAppDeployer.java:80)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:405)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:372)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)


com.google.apphosting.vmruntime.jetty9.AppengineApiConfiguration configure: No appengine API jar included in WEB-INF/lib! Please update your SDK!
java.lang.ClassNotFoundException: com.google.appengine.api.ThreadManager
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:549)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:475)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
    at com.google.apphosting.vmruntime.jetty9.AppengineApiConfiguration.configure(AppengineApiConfiguration.java:118)
    at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:491)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1336)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
    at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doStart(VmRuntimeWebAppContext.java:189)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppDeployer.doStart(VmRuntimeWebAppDeployer.java:80)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:405)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:372)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1510)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1435)
```

So the API jar was detected as missing, but the context should have added another to replace it.  So this looks like a bug.

**Comment by gregw** [comment] 2016-07-13 01:28
@ifigotin Can you ask the reporter on the internal issue to provide all of the output from their failed images.   Specifically I would like to see the very next line after the stack reported in the log above, as I would like to know if it says something like:
```
INFO: Added appengine-api-1.0-sdk-1.9.38.jar to webapp classpath
```
if it does not, then we have an issue that the API jar was not correctly added to the context classpath.  If it does, then we have added it, but it was not sufficient for this application, so we need to see subsequent log output to see what was unable to load.

**Comment by ifigotin** [comment] 2016-07-13 02:57
@gregw Yep, I asked the customer, and let's see what the customer says.

**Comment by gregw** [comment] 2016-07-13 06:04
@ifigotin See PR #299.  Rather than a full revert (as suggested by @ludoch ) this is a modification of the last PR to keep the updated mechanisms (the policy contained in a single class, reflected transaction rollback), but applies the previous classloader policy of exposing the API jar used by the container.

However, I think we need to see more info from the customer to decide if we should rollback or not, so I've just got this ready in case the issue is simple the classloader policy and not the mechanism.

Are there other webapplications that I can use to test against?  Currently I'm just testing against stage 3 of the guestbook.   Obviously we need more extensive testing.

**Comment by ifigotin** [comment] 2016-07-13 16:19
@gregw I think that PR is merged already, right?

**Comment by gregw** [comment] 2016-07-13 21:23
@ifigotin yep - Ludo merged.  So we still need to test this and also test the unmerged to see what went wrong.  So any realistic test webapps you can point me at would be useful.

**Closed** 2016-09-08 01:08 UTC
